THEME_DARK_PRIMARY: "#CC0000"
THEME_DARK_ACCENT: "#FFB300"
THEME_DARK_SECONDARY: "#444444"
THEME_DARK_SUCCESS: "#00C853"
THEME_DARK_WARNING: "#FFB300"
THEME_DARK_ERROR: "#880000"
THEME_DARK_INFO: "#CC0000"
